import React from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { palette, commonStyles } from "../../theme";
import { AppCard } from "../../components/AppCard";
import { ScreenHeader } from "../../components/ScreenHeader";

export function TermsScreen({ onBack }: { onBack: () => void }) {
  return (
    <ScrollView contentContainerStyle={styles.screenContent}>
      <ScreenHeader title="Terms of Service" subtitle="Last updated March 2026" onBack={onBack} />

      <AppCard style={commonStyles.stackMd}>
        <Text style={styles.termsTitle}>1. Introduction</Text>
        <Text style={styles.termsText}>
          AURA Guide provides AI-driven life coaching and academic planning tools. By using our service, you agree to
          the collection and processing of your academic data to provide personalized recommendations.
        </Text>

        <Text style={styles.termsTitle}>2. Data Privacy</Text>
        <Text style={styles.termsText}>
          We take your data seriously. Your personal information, university details, and goals are stored securely and
          only used to enhance your experience within the AURA ecosystem.
        </Text>

        <Text style={styles.termsTitle}>3. AI Usage</Text>
        <Text style={styles.termsText}>
          Recommendations and coaching prompts are generated by artificial intelligence. While we strive for accuracy,
          users should exercise personal judgement in their career and academic decisions.
        </Text>

        <Text style={styles.termsTitle}>4. Community Conduct</Text>
        <Text style={styles.termsText}>
          Users are expected to interact with the platform in a professional manner. Any misuse of AI tools or community
          features may result in account suspension.
        </Text>
      </AppCard>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  screenContent: {
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 24,
    gap: 16,
  },
  termsTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: palette.text,
    marginBottom: 4,
  },
  termsText: {
    color: palette.muted,
    lineHeight: 22,
    marginBottom: 8,
  },
});
